theme: jekyll-theme-minimal
logo: https://cdn-images-1.medium.com/max/736/1*zwd0nG_HgpLMe-LpAIKltQ@2x.jpeg
title: VLNTR
description: We are a passionate community of digital natives who want to change the world for the better.
